[tool.poetry]
name = "pypush"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"] # TODO: Change this
license = "SSPL-1.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"
cryptography = "^41.0.5"
wheel = "^0.41.3"
srp = "^1.0.20"
pbkdf2 = "^1.3"
unicorn = "^2.0.1.post1"
rich = "^13.7.0"
trio = "^0.23.1"

[tool.poetry.group.dev.dependencies]
printer = "^2.0.0"
ipython = "^8.17.2"
asn1crypto = "^1.5.1"
websockets = "^12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
